# Generated by Django 5.2.9 on 2026-01-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_employee_alter_project_name_alter_task_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
